version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    environment:
      - POSTGRES_USER=user
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=user
      - USE_DOCKER=yes
    volumes:
      - .:/app
      - ../shared:/app/shared
    ports:
      - "8003:8000"
    links:
      - postgres
