# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('primary_class', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='wav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Wav'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Segment'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.User'),
        ),
    ]
