# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0004_auto_20161104_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='e_class',
            new_name='event_class',
        ),
    ]
