# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0005_auto_20161104_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
