# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0006_project_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wav',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload date'),
            preserve_default=False,
        ),
    ]
