# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0007_wav_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wav',
            name='project',
        ),
        migrations.AddField(
            model_name='wav',
            name='projects',
            field=models.ManyToManyField(to='annotation_tool.Project'),
        ),
    ]
