# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0008_auto_20161108_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wav',
            name='projects',
        ),
        migrations.AddField(
            model_name='wav',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Project'),
            preserve_default=False,
        ),
    ]
