# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0009_auto_20161108_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='wav',
            name='name',
            field=models.CharField(default='wav_name', max_length=100),
            preserve_default=False,
        ),
    ]
