# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0011_auto_20161109_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tag_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
