# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0012_auto_20161109_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
