# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0015_auto_20161109_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.AddField(
            model_name='class',
            name='tags',
            field=models.ManyToManyField(to='annotation_tool.Tag'),
        ),
    ]
