# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0018_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='annotation_tool.Tag'),
        ),
    ]
