# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0019_auto_20161109_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='annotation_tool.Tag'),
        ),
    ]
