# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0020_auto_20161109_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='annotation date'),
            preserve_default=False,
        ),
    ]
