# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation_tool', '0022_auto_20161109_1646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together=set([('segment', 'user')]),
        ),
    ]
