# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0023_auto_20161111_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='wav',
            name='file',
            field=models.FileField(default=0, max_length=500, upload_to='/home/bmelendez/django_test/'),
            preserve_default=False,
        ),
    ]
