# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0025_auto_20161111_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='difficulty',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segment',
            name='number_of_annotations',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
