# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0026_auto_20161115_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='priority',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
