# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0028_auto_20161118_0943'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('annotation', 'event_class', 'start_time', 'end_time')]),
        ),
    ]
