# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0029_auto_20161121_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='color',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
