# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0031_auto_20161121_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_class',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Class'),
        ),
    ]
