# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0032_auto_20161122_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.FloatField(blank=True),
        ),
    ]
