# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0034_auto_20161123_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
