# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0035_auto_20161123_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Class'),
        ),
    ]
