# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0036_auto_20161123_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Class'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.FloatField(null=True),
        ),
    ]
