# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0037_auto_20161123_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.FloatField(default=0.0),
        ),
    ]
