# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0038_auto_20161123_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
