# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0039_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='shortcut',
            field=models.CharField(default='m', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wav',
            name='file',
            field=models.FileField(max_length=500, upload_to='/home/bmelendez/musicspeech_annotation_project/django_test/'),
        ),
    ]
