# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0040_auto_20161125_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='annotation',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
