# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0041_auto_20161207_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.FloatField(blank=True, null=True)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Segment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([('segment', 'start_time', 'end_time')]),
        ),
    ]
