# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0042_auto_20161207_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='number_of_annotations',
        ),
        migrations.AlterField(
            model_name='segment',
            name='priority',
            field=models.FloatField(default=2.0),
        ),
    ]
