# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0044_class_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wav',
            name='file',
            field=models.FileField(max_length=500, upload_to='/app/django_test/'),
        ),
    ]
