# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0045_auto_20161225_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overlap',
            field=models.BooleanField(default=False),
        ),
    ]
