# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0046_project_overlap'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('project', 'shortcut'), ('project', 'color'), ('project', 'name')]),
        ),
    ]
