# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 06:15
from __future__ import unicode_literals

import annotation_tool.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0047_auto_20161227_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProminence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prominence', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very low'), (2, 'Low'), (3, 'Mid'), (4, 'Loud'), (5, 'Very loud')], null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Class')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='annotation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Annotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='region',
            name='tags',
            field=models.ManyToManyField(blank=True, to='annotation_tool.Tag'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='status',
            field=models.CharField(choices=[('finished', 'finished'), ('unfinished', 'unfinished')], default='unfinished', max_length=10),
        ),
        migrations.AlterField(
            model_name='wav',
            name='file',
            field=models.FileField(max_length=500, upload_to=annotation_tool.models.get_wav_file_path),
        ),
        migrations.RemoveField(
            model_name='region',
            name='class_name',
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([('annotation', 'start_time', 'end_time')]),
        ),
        migrations.AddField(
            model_name='classprominence',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='annotation_tool.Region'),
        ),
    ]
