# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0048_auto_20170110_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='segment',
        ),
    ]
