# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0049_remove_region_segment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classprominence',
            options={'ordering': ('class_obj__name',)},
        ),
    ]
