# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-21 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0050_auto_20170119_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('shortcut',)},
        ),
    ]
