# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0051_auto_20170121_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='reliable',
            field=models.BooleanField(default=False),
        ),
    ]
