# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0052_segment_reliable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='shortcut',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
