# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0053_auto_20170203_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.FloatField(),
        ),
    ]
