# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0054_auto_20170207_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('time', models.FloatField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Annotation')),
            ],
        ),
    ]
