# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0058_auto_20170315_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
