# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0059_auto_20170315_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classprominence',
            name='prominence',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, 'Most salient')], null=True),
        ),
    ]
