# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0060_auto_20170420_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='classinstance',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Class'),
        ),
        migrations.AddField(
            model_name='classinstance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Project'),
        ),
        migrations.RemoveField(
            model_name='class',
            name='color',
        ),
        migrations.RemoveField(
            model_name='class',
            name='project',
        ),
        migrations.RemoveField(
            model_name='class',
            name='shortcut',
        ),
        migrations.RemoveField(
            model_name='class',
            name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='classinstance',
            unique_together=set([('project', 'class_obj')]),
        ),
    ]
